import Brand from '@/app/brand';
import {heroSlides} from '@/lib/hero-slides';
import {setting} from '@/lib/server';
export const metadata={title:'Impressum · QONSUL'};
export default function Impressum(){const email=setting('PUBLIC_CONTACT_EMAIL');return <><header className="header"><a className="brand" href="/"><Brand/></a><a href="/" className="button button-outline">← Zur Startseite</a></header><main className="legal-page"><div className="eyebrow">ANBIETERINFORMATIONEN</div><h1>Impressum</h1><p className="preview-note">Private Entwicklungsvorschau. Die eingetragenen Unternehmensdaten stammen aus den Betreiberangaben. Redaktionelle Verantwortung, Telefonnummer und Verbraucherstreitbeilegung müssen vor der öffentlichen Freigabe noch bestätigt werden.</p>
<section><h2>Anbieter</h2><p>{setting('LEGAL_ENTITY_NAME')||'Vollständiger Unternehmensname und Rechtsform: noch zu ergänzen.'}</p><p>{setting('LEGAL_ADDRESS')||'Ladungsfähige Anschrift: noch zu ergänzen.'}</p><p>Vertreten durch: {setting('LEGAL_REPRESENTATIVE')||'noch zu ergänzen.'}</p></section>
<section><h2>Kontakt</h2><p>{email?<a href={`mailto:${email}`}>{email}</a>:'Geschäftliche E-Mail: noch zu ergänzen.'}</p><p>{setting('LEGAL_PHONE')?`Telefon: ${setting('LEGAL_PHONE')}`:'Telefon bzw. weiterer unmittelbarer Kontaktweg: noch zu bestätigen.'}</p></section>
<section><h2>Register und steuerliche Angaben</h2><p>{setting('LEGAL_REGISTER')||'Registergericht und Registernummer: noch zu ergänzen.'}</p><p>{setting('LEGAL_VAT_ID')?`Umsatzsteuer-Identifikationsnummer: ${setting('LEGAL_VAT_ID')}`:'Umsatzsteuer-Identifikationsnummer, sofern vorhanden: noch zu ergänzen.'}</p></section>
<section><h2>Redaktionell verantwortlich</h2><p>{setting('LEGAL_EDITORIAL_RESPONSIBLE')||'Verantwortliche Person mit ladungsfähiger Anschrift nach § 18 Abs. 2 MStV: vor Veröffentlichung zu bestätigen.'}</p><p>Die redaktionellen Artikel vermitteln allgemeine Qualitäts-, Risiko- und Datenmethoden. Als „Beispielszenario“ gekennzeichnete Inhalte sind keine Kundenreferenzen. KI- und Regelvorschläge müssen im konkreten System überprüft werden.</p></section>
<section><h2>Verbraucherstreitbeilegung</h2><p>{setting('LEGAL_DISPUTE_RESOLUTION')||'Erklärung zur Bereitschaft oder Verpflichtung zur Teilnahme an einem Streitbeilegungsverfahren: abhängig von Mitarbeiterzahl und Angebot vor Veröffentlichung festzulegen.'}</p></section>
<section id="bildnachweise"><h2>Bildnachweise</h2><p>Die Branchenmotive sind Fotografien, genutzt unter der <a href="https://unsplash.com/license" target="_blank" rel="noreferrer">Unsplash-Lizenz</a>. Sie illustrieren Anwendungsfelder und zeigen keine QONSUL-Kundenprojekte. Abgebildete Unternehmen oder Produkthersteller sind keine behaupteten Referenzen oder Partner. Grafische Konzeptdarstellungen zeigen keine Kunden- oder Projektdaten.</p><ul className="image-credits">{heroSlides.map(slide=><li key={slide.id}><strong>{slide.industry}</strong><span>{slide.alt}. Foto: <a href={slide.source} target="_blank" rel="noreferrer">{slide.author} / Unsplash ↗</a></span></li>)}</ul></section><a className="text-link" href="/datenschutz">Datenschutzhinweise lesen ↗</a></main></>}
