'use client';
import { BrandMark } from '@/app/brand';
import { useEffect, useRef, useState, type FormEvent } from 'react';
import { CATEGORIES, DATA_KINDS, CONSENT_VERSION, categoryHints, type DataKind, type Analysis, type Category, type Cause } from '@/lib/analysis';
import { reportHtml } from '@/lib/report';
import { downloadIshikawaPdf } from '@/lib/ishikawa-pdf';
import { emitAnalyticsHook } from '@/lib/analytics-hooks';
import { currentAnalyticsSessionId } from '@/lib/analytics-session';

const examples=['Sporadische Ausfälle bei hohen Temperaturen','Steigende Ausschussquote in der Fertigung','Qualität schwankt zwischen Lieferchargen'];
const initialStatus={ai:false,crm:false,productionReady:false,contactEmail:''};
export function downloadHtml(analysis:Analysis){const url=URL.createObjectURL(new Blob([reportHtml(analysis)],{type:'text/html;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='Qonsul-Ishikawa-Report.html';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export default function IshikawaLab({launch}:{launch?:{problem:string;id:number}}){
  const [input,setInput]=useState(''),[problem,setProblem]=useState(''),[causes,setCauses]=useState<Cause[]>([]),[selected,setSelected]=useState<Category>('Produkt'),[draft,setDraft]=useState(''),[editing,setEditing]=useState<string|null>(null),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[error,setError]=useState(''),[status,setStatus]=useState(initialStatus),[aiConsent,setAiConsent]=useState(false),[leadOpen,setLeadOpen]=useState(false),[mode,setMode]=useState<Analysis['mode']>('manual');
  const [saving,setSaving]=useState(false),[saveError,setSaveError]=useState(''),[saved,setSaved]=useState<{url:string;status:'accepted';reference:string;consultationRequested:boolean}|null>(null),[resetOpen,setResetOpen]=useState(false);
  const [availableData,setAvailableData]=useState<DataKind[]>([]),[pendingProblem,setPendingProblem]=useState('');
  const causeInput=useRef<HTMLInputElement>(null),board=useRef<HTMLDivElement>(null),reportToken=useRef(''),generation=useRef(0),diagnosticFlowId=useRef(''),completedSteps=useRef(new Set<string>());
  useEffect(()=>{fetch('/api/status').then(r=>r.json() as Promise<typeof initialStatus>).then(setStatus).catch(()=>{});},[]);
  useEffect(()=>{if(!launch?.problem)return;queueMicrotask(()=>{if(busy||saving){setError('Bitte warten Sie, bis der aktuelle Vorgang abgeschlossen ist.');return;}if(problem){setPendingProblem(launch.problem);setResetOpen(true);document.getElementById('analyse')?.scrollIntoView({behavior:'smooth'});}else start(launch.problem);});},[launch?.id]);
  const analysis:Analysis={problem,causes,mode,availableData};
  const userCount=causes.filter(c=>c.source==='user').length,generatedCount=causes.length-userCount;
  function markStep(stepKey:'problem'|'causes'|'report',stepSequence:number){if(!diagnosticFlowId.current||completedSteps.current.has(stepKey))return;completedSteps.current.add(stepKey);emitAnalyticsHook('diagnostic_step_completed',{diagnosticFlowId:diagnosticFlowId.current,stepKey,stepSequence});}
  function start(value=input){if(value.trim().length<10){setError('Bitte beschreiben Sie Ihr Problem in mindestens 10 Zeichen.');return;}diagnosticFlowId.current=crypto.randomUUID();completedSteps.current.clear();emitAnalyticsHook('ishikawa_started');emitAnalyticsHook('diagnostic_started',{diagnosticFlowId:diagnosticFlowId.current});markStep('problem',1);setInput(value);setProblem(value.trim());setError('');setNotice('Ergänzen Sie zwei oder drei eigene Beobachtungen — oder starten Sie direkt mit Vorschlägen.');setTimeout(()=>board.current?.scrollIntoView({behavior:'smooth',block:'start'}),60);}
  function invalidate(){setSaved(null);reportToken.current='';}
  function reset(){generation.current++;diagnosticFlowId.current='';completedSteps.current.clear();setProblem('');setInput('');setCauses([]);setAvailableData([]);setPendingProblem('');setSelected('Produkt');setAiConsent(false);setMode('manual');setDraft('');setEditing(null);setNotice('');setError('');setLeadOpen(false);setResetOpen(false);invalidate();}
  function addCause(e:FormEvent){e.preventDefault();const text=draft.trim();if(text.length<3)return;if(!editing&&causes.filter(c=>c.category===selected&&c.source==='user').length>=3){setError('Pro Kategorie können Sie drei eigene Ursachen ergänzen.');return;}markStep('causes',2);setCauses(previous=>editing?previous.map(c=>c.id===editing?{...c,text}:c):[...previous,{id:crypto.randomUUID(),category:selected,text,source:'user'}]);setDraft('');setEditing(null);setError('');invalidate();}
  async function boost(){setBusy(true);setError('');const run=++generation.current;try{const response=await fetch('/api/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...analysis,causes:causes.filter(c=>c.source==='user'),aiConsent}),signal:AbortSignal.timeout(12000)});const data=await response.json() as {error?:string;causes:Cause[];mode:Analysis['mode'];notice:string};if(!response.ok)throw new Error(data.error||'Analyse fehlgeschlagen.');if(run!==generation.current)return;setCauses(previous=>[...previous.filter(c=>c.source==='user'),...data.causes]);setMode(data.mode);setNotice(data.notice);invalidate();}catch(err){setError(err instanceof Error&&err.name==='TimeoutError'?'Die Verbindung dauert zu lange. Ihre Ursachen bleiben erhalten. Bitte erneut versuchen.':err instanceof Error?err.message:'Bitte erneut versuchen.');}finally{setBusy(false);}}
  async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();emitAnalyticsHook('ishikawa_completed');setSaving(true);setSaveError('');const data=new FormData(e.currentTarget);if(!reportToken.current)reportToken.current=crypto.randomUUID()+crypto.randomUUID();try{const response=await fetch('/api/reports',{method:'POST',headers:{'Content-Type':'application/json'},signal:AbortSignal.timeout(25000),body:JSON.stringify({analysis,name:data.get('name'),email:data.get('email'),company:data.get('company'),website:data.get('website'),storageConsent:data.get('storageConsent')==='on',crmConsent:data.get('crmConsent')==='on',trendConsent:data.get('trendConsent')==='on',demoConfirmed:data.get('demoConfirmed')==='on',consentVersion:CONSENT_VERSION,reportToken:reportToken.current,analyticsSessionId:currentAnalyticsSessionId(),diagnosticFlowId:diagnosticFlowId.current||null})});const result=await response.json() as {error?:string;url:string;status:'accepted';reference:string;consultationRequested:boolean};if(!response.ok)throw new Error(result.error);markStep('report',3);emitAnalyticsHook('diagnostic_completed',{diagnosticFlowId:diagnosticFlowId.current});emitAnalyticsHook('ishikawa_accepted');setSaved(result);}catch(err){setSaveError(err instanceof Error?err.message:'Speichern fehlgeschlagen. Bitte erneut versuchen.');}finally{setSaving(false);}}
  return <section id="analyse" className="lab" aria-label="Interaktives Ishikawa Analyse-Tool">
    <div className="lab-top"><div className="lab-title"><span className="lab-mark"><BrandMark/></span><div><strong>QONSUL Quality Diagnostic</strong><span>Strukturierte Ursachenanalyse für Produkt und Prozess.</span></div></div><span className="pill"><span className="live-dot"/> Kostenlos & ohne Anmeldung starten</span></div>
    <div className="steps" aria-label="Analyseschritte"><span className="active"><b>{problem?'✓':'01'}</b> Problem beschreiben</span><i/><span className={problem?'active':''}><b>{generatedCount?'✓':'02'}</b> Ursachen entdecken</span><i/><span className={leadOpen||saved?'active':''}><b>{saved?'✓':'03'}</b> Klarheit mitnehmen</span></div>
    {!problem?<div className="lab-entry"><div className="eyebrow">DAS PROBLEM IST DER ANFANG. NICHT DAS ENDE.</div><h2>Welches Qualitätsproblem beschäftigt Sie?</h2><p>Beschreiben Sie Ihre Beobachtung aus Entwicklung, Validierung oder Produktion.</p><form onSubmit={e=>{e.preventDefault();start();}}><label className="sr-only" htmlFor="problem">Ihr Qualitäts- oder Testproblem</label><div className="problem-input"><span aria-hidden="true">⌕</span><input id="problem" value={input} onChange={e=>setInput(e.target.value)} minLength={10} maxLength={600} required placeholder="z. B. Bauteile fallen bei der thermischen Validierung sporadisch aus."/><button className="button button-green" type="submit">Analyse starten <span>↗</span></button></div><div className="examples"><span>Zum Beispiel:</span>{examples.map(t=><button type="button" key={t} onClick={()=>start(t)}>{t} <span>↗</span></button>)}</div></form></div>:<div className="active-problem"><div><span className="eyebrow">IHR QUALITÄTSPROBLEM</span><h2>{problem}</h2></div><button className="quiet-button" onClick={()=>setResetOpen(true)} disabled={busy||saving}>Neue Analyse ↺</button></div>}
    {resetOpen&&<div className="inline-confirm"><span>Neue Analyse starten? Nicht heruntergeladene Änderungen gehen verloren.</span><button className="button button-outline" onClick={()=>{setResetOpen(false);setPendingProblem('');}}>Abbrechen</button><button className="button button-green" disabled={busy||saving} onClick={()=>{const next=pendingProblem;reset();if(next)start(next);}}>Neu starten</button></div>}
    <div ref={board} className={'board-preview '+(problem?'board-active':'')}>
      <div className="board-heading"><span><span className="live-dot"/>{problem?'IHRE URSACHENLANDKARTE':'SO WIRD AUS EINEM PROBLEM EIN KLARER PLAN'}</span><span>{problem?`${userCount} eigene · ${generatedCount} ergänzte Hypothesen`:'6 Perspektiven. Ein Gesamtbild.'}</span></div>
      <div className="fish-layout"><div className="fish-categories"><svg className="fish-lines" viewBox="0 0 900 400" preserveAspectRatio="none" aria-hidden="true"><path d="M0 200 H940 M110 20 L230 200 L110 380 M390 20 L510 200 L390 380 M670 20 L790 200 L670 380" fill="none" stroke="var(--diagram-line)" strokeWidth="1.4" vectorEffect="non-scaling-stroke"/></svg>{CATEGORIES.map((category,i)=><div className={'cause-category '+(problem&&selected===category?'selected':'')} key={category}><button className="category-title" disabled={!problem||busy||saving} onClick={()=>{setSelected(category);setEditing(null);setDraft('');causeInput.current?.focus();}}><span className="category-number">0{i+1}</span><strong>{category}</strong><span className="category-count">{problem?causes.filter(c=>c.category===category).length:'+'}</span></button>{!problem?<span className="category-placeholder">Ursachen sichtbar machen</span>:<><ul className="cause-list">{causes.filter(c=>c.category===category).map((cause,j)=><li className={'cause cause-'+cause.source} key={cause.id} style={{animationDelay:`${j*70+i*45}ms`}}><details><summary><span className="cause-source">{cause.source==='user'?'●':cause.source==='ai'?'✧':'◇'}</span>{cause.text}</summary><div className="cause-details"><span>{cause.source==='user'?'Eigene Beobachtung':cause.source==='ai'?'KI-Hypothese · prüfen':'Regelkatalog · Hypothese prüfen'}</span>{cause.check&&<p>{cause.check}</p>}{cause.data&&cause.data.length>0&&<p className="required-data"><b>Benötigte Daten:</b> {cause.data.join(' · ')}</p>}{cause.metric&&<small>Messbezug: {cause.metric}</small>}<div>{cause.source==='user'&&<button disabled={busy||saving} onClick={()=>{setSelected(category);setEditing(cause.id);setDraft(cause.text);causeInput.current?.focus();}}>Bearbeiten</button>}<button disabled={busy||saving} onClick={()=>{setCauses(previous=>previous.filter(c=>c.id!==cause.id));if(editing===cause.id){setEditing(null);setDraft('');}invalidate();}}>Entfernen</button></div></div></details></li>)}</ul><button className="add-cause" disabled={busy||saving||causes.filter(c=>c.category===category&&c.source==='user').length>=3} onClick={()=>{setSelected(category);setEditing(null);setDraft('');causeInput.current?.focus();}}>+ Eigene Ursache</button></>}</div>)}</div><div className="fish-problem"><span>AUSGANGSPUNKT</span><strong>{problem||'Ihr Qualitätsproblem'}</strong><small>Hier beginnt die Veränderung.</small></div></div>
      <div className="board-bottom"><span>● Ihre Beobachtungen <span className="separator">+</span> {mode==='ai'?'✧ KI-Hypothesen':'◇ Ergänzende Perspektiven'}</span><a href="#methode">Die Ishikawa-Methode ↗</a></div>
    </div>
    {problem&&<div className="workbench"><form onSubmit={addCause} className="cause-form"><label htmlFor="cause-category">{editing?'Beobachtung bearbeiten':'Ihre Perspektive ergänzen'}</label><div><select id="cause-category" value={selected} disabled={!!editing||busy||saving} onChange={e=>setSelected(e.target.value as Category)}>{CATEGORIES.map(c=><option key={c}>{c}</option>)}</select><input ref={causeInput} aria-label="Eigene Ursache" value={draft} onChange={e=>setDraft(e.target.value)} placeholder={categoryHints[selected]} minLength={3} maxLength={220} required disabled={busy||saving}/><button className="button button-outline" disabled={busy||saving} type="submit">{editing?'Speichern':'Hinzufügen'} +</button></div>{editing&&<button className="quiet-button" type="button" onClick={()=>{setEditing(null);setDraft('');}}>Bearbeitung abbrechen</button>}</form><div className="boost-section"><div><strong>Was übersehen wir vielleicht?</strong><p>{status.ai?'Neue Hypothesen aus sechs Perspektiven – mit Prüfschritten und benötigten Daten.':'Vorschau: Fachliche Vorschläge aus dem Regelkatalog. Keine KI verbunden.'}</p></div><button className="button button-green boost-button" disabled={busy||saving||(status.ai&&!aiConsent)} onClick={boost}>{busy?<><span className="fish-spinner" aria-hidden="true">⋙</span> Perspektiven werden ergänzt …</>:<><span>✧</span> {status.ai?'Hypothesen mit KI ergänzen':generatedCount?'Vorschläge aktualisieren':'Blinde Flecken ergänzen'}</>}</button></div>{status.ai&&<label className="check-label ai-consent"><input type="checkbox" checked={aiConsent} onChange={e=>setAiConsent(e.target.checked)}/> Ich stimme der Übermittlung der bereinigten Problembeschreibung und eigener Ursachen an OpenAI zu. Keine Namen, Zugangsdaten oder Geschäftsgeheimnisse eingeben. <a href="/datenschutz">Details</a></label>}<div aria-live="polite" className="analysis-notice">{notice}</div><div className="hypothesis-note">◎ Vorschläge sind Hypothesen. Ihr Team bestätigt Ursachen mit Daten und Experimenten.</div></div>}
    {problem&&<section className="data-inventory" aria-labelledby="data-heading"><span className="eyebrow">DIE DATENGRUNDLAGE</span><h3 id="data-heading">Welche Daten stehen Ihnen zur Verfügung?</h3><p>Markieren Sie vorhandene Datentypen. Hier werden keine Dateien hochgeladen oder Messwerte analysiert.</p><div className="data-options">{DATA_KINDS.map(kind=><label key={kind}><input type="checkbox" checked={availableData.includes(kind)} disabled={busy||saving} onChange={e=>{setAvailableData(previous=>e.target.checked?[...previous,kind]:previous.filter(k=>k!==kind));invalidate();}}/>{kind}</label>)}</div>{generatedCount>0&&<p className="data-coverage" aria-live="polite"><b>{causes.filter(c=>c.data?.length&&c.data.every(d=>availableData.includes(d))).length} von {causes.filter(c=>c.data?.length).length}</b> Vorschlägen sind vollständig mit den von Ihnen markierten Datentypen abgedeckt. Verfügbarkeit sagt noch nichts über Datenqualität oder einen Ursachennachweis aus.</p>}</section>}{error&&<p role="alert" className="error-message">{error}</p>}
    {problem&&causes.length>0&&<div className="capture"><div className="capture-summary"><span className="report-icon">▤</span><div><h3>Erkenntnisse, die Ihr Team weiterbringen.</h3><p>Sichern Sie Ihre Analyse oder besprechen Sie die nächsten Schritte mit uns.</p></div><button className="button button-dark" onClick={()=>setLeadOpen(!leadOpen)} disabled={busy||saving} aria-expanded={leadOpen}>Report & Austausch ↗</button></div><button className="local-download" disabled={busy||saving} onClick={()=>downloadIshikawaPdf(analysis,true)}>↧ Ishikawa direkt als DIN-A4-PDF herunterladen · ohne Kontaktdaten</button>
      {leadOpen&&<div className="lead-content">{saved?<div className="save-success" role="status"><span className="success-mark">✓</span><h3>Ihre Analyse ist gesichert.</h3><p>Ihr persönlicher Link ist 30 Tage gültig. Jeder mit dem Link kann den Report lesen und löschen; bitte vertraulich behandeln.</p><a className="button button-green" href={saved.url}>Gespeicherten Report öffnen ↗</a><p className="crm-notice">{saved.consultationRequested?'Ihre Beratungsanfrage wurde mit der Analyse sicher an QONSUL übermittelt.':'Keine Kontaktaufnahme und keine CRM-Übermittlung angefordert.'}</p></div>:<form onSubmit={save} className="lead-form"><div className="lead-heading"><h3>Für Ihr Team sichern.</h3><p>Optional mit persönlichem Report-Link und fachlichem Austausch.</p></div>{!status.productionReady&&<p className="preview-note">Private Vorschau · Bitte ausschließlich fiktive Testdaten verwenden. Die Anbieterangaben sind noch nicht freigegeben.</p>}<div className="lead-fields"><label>Name<input name="name" required maxLength={100} autoComplete="name" placeholder="Vor- und Nachname"/></label><label>Geschäftliche E-Mail<input name="email" type="email" required maxLength={254} autoComplete="email" placeholder="name@unternehmen.de"/></label><label>Unternehmen<input name="company" required maxLength={150} autoComplete="organization" placeholder="Ihr Unternehmen"/></label></div><div className="honey" aria-hidden="true"><label>Website<input name="website" tabIndex={-1} autoComplete="off"/></label></div><label className="check-label"><input name="storageConsent" type="checkbox" required/> <span>Ich willige ein, dass meine Kontaktdaten und die vollständige Analyse zur Bereitstellung des Reports für bis zu 30 Tage gespeichert werden. Widerruf durch Löschen über den Report-Link. <a href="/datenschutz">Datenschutzhinweise</a></span></label><label className="check-label"><input name="crmConsent" type="checkbox"/> <span>Optional: Ich wünsche eine persönliche Beratung zu dieser Analyse und stimme der Kontaktaufnahme per E-Mail sowie der Übermittlung von Kontakt und Analyse an das QONSUL Cockpit zu. Kein Newsletter.</span></label><label className="check-label"><input name="trendConsent" type="checkbox"/> <span>Optional: Anonyme Kategoriezähler für die Trendanalyse nutzen. Keine Texte oder Kontaktdaten.</span></label>{!status.productionReady&&<label className="check-label"><input name="demoConfirmed" type="checkbox" required/><span>Ich verwende ausschließlich fiktive Testdaten für diese private Vorschau.</span></label>}{saveError&&<p role="alert" className="error-message">{saveError}</p>}<div className="lead-submit"><span>Kein E-Mail-Versand. Ihr Download-Link erscheint direkt hier.</span><button className="button button-green" disabled={saving||busy}>{saving?'Analyse wird gesichert …':'Analyse sichern ↗'}</button></div></form>}</div>}
    </div>}
    <div className="lab-trust"><span>◈ Keine vertraulichen Daten eingeben</span><span>◎ Sie entscheiden, was gespeichert wird</span><span>↧ Analyse als Report mitnehmen</span></div>
  </section>;
}
