'use client';
import IshikawaLab from './ishikawa-lab';
import SiteContent, { Metrics } from './site-content';
export default function QualitySite() {
  return <>
    <header className="header"><a className="brand" href="/" aria-label="Qonsul Startseite"><img src="/qonsul-logo.png" alt="Qonsul" /></a><nav><a href="#leistungen">Leistungen ⌄</a><a href="#ueber-uns">Über uns</a><a href="#insights">Insights & Blog</a></nav><details className="mobile-menu"><summary aria-label="Navigation öffnen">☰</summary><div><a href="#leistungen">Leistungen</a><a href="#ueber-uns">Über uns</a><a href="#insights">Insights & Blog</a></div></details><a className="button button-dark header-cta" href="#analyse">Problem analysieren <span>↗</span></a></header>
    <a className="skip-link" href="#analyse">Direkt zur Analyse</a><main>
      <section className="hero"><div className="hero-copy"><div className="eyebrow"><span className="live-dot"/> DATA-DRIVEN QUALITY ENGINEERING</div><h1>Weniger Fehlersuche.<br/><span>Mehr Fortschritt.</span></h1><p>Schluss mit blinder Fehlersuche. Wir machen Software-Qualität messbar — und Ihr Engineering-Team wirksamer.</p><div className="hero-points"><span>↗ Daten statt Bauchgefühl</span><span>◎ Qualität, die bleibt</span></div></div><div className="hero-aside"><span>VON DER URSACHE ZUR WIRKUNG</span><div className="signal-graphic">{Array.from({length:24},(_,i)=><i key={i}/>)}</div><small>Komplexität verstehen. Klarheit schaffen.</small></div></section>
      <IshikawaLab /><Metrics />
      <section id="leistungen" className="services section-wrap"><div className="section-heading"><div><div className="eyebrow">QUALITÄT IST KEIN ZUFALL.</div><h2>Gute Software braucht<br/>mehr als gute Tests.</h2></div><p>Wir verbinden Engineering, Automatisierung und Daten.<br/>Damit aus Erkenntnissen echte Verbesserungen werden.</p></div><div className="service-grid">{[['01','Quality Engineering','Qualität von Anfang an.','Von der ersten Anforderung bis zum Betrieb: Wir verankern Qualität in Ihrem gesamten Entwicklungsprozess.'],['02','Test-Automation','Vertrauen in jeden Release.','Robuste Tests, schnelles Feedback und verlässliche Pipelines. Automatisierung, die Ihrem Team Arbeit abnimmt.'],['03','DORA-Metriken','Fortschritt, den Sie messen.','Verstehen Sie Ihren Delivery-Prozess. Erkennen Sie Engpässe und verbessern Sie, was wirklich Wirkung zeigt.']].map(s=><a href={`/leistungen/${["quality-engineering","test-automation","dora-metriken"][Number(s[0])-1]}`} className="service-card" key={s[0]}><div><span className="service-number">{s[0]}</span><span className="service-arrow">↗</span></div><h3>{s[1]}</h3><strong>{s[2]}</strong><p>{s[3]}</p><span className="text-link">Gemeinsam Potenziale finden ↗</span></a>)}</div></section>
      <SiteContent /><section className="bottom-cta" id="ueber-uns"><div><div className="eyebrow">QONSUL. ENGINEERING MIT WEITBLICK.</div><h2>Die richtigen Fragen.<br/>Die nächsten Schritte.</h2><p className="about-description">Qonsul verbindet Qualitätsdenken mit Engineering-Praxis. Unser Ansatz: zuhören, Zusammenhänge verstehen und gemeinsam mit Ihrem Team wirksame Verbesserungen entwickeln.</p></div><a className="button button-lime" href="#analyse">Ihr Problem gemeinsam verstehen ↗</a></section>
    </main><footer><a className="brand" href="/"><img src="/qonsul-logo.png" alt="Qonsul"/></a><span>© {new Date().getFullYear()} Qonsul · Quality with clarity.</span><div><a href="/impressum">Impressum</a><a href="/datenschutz">Datenschutz</a><a href="#analyse">Kontakt ↗</a></div></footer>
  </>;
}
