import {articles,services} from '@/lib/content';

function EngineeringVisual({kind}:{kind:number}){
  if(kind===0)return <div className="engineering-visual visual-product" aria-hidden="true"><div className="precision-rings"><i/><i/><i/><i/><span>Q</span></div><span className="visual-label top-left">ANFORDERUNG</span><span className="visual-label bottom-right">NACHWEIS</span><div className="visual-caption">VON DER IDEE ZUM ROBUSTEN PRODUKT</div></div>;
  if(kind===1)return <div className="engineering-visual visual-risk" aria-hidden="true"><div className="risk-matrix">{Array.from({length:64},(_,i)=><i key={i} style={{opacity:.12+((i%8)+Math.floor(i/8))/19}}/>)}</div><span className="visual-label top-left">WIRKUNG</span><span className="visual-label bottom-right">UNSICHERHEIT</span><div className="visual-caption">RISIKEN IN IHREM ZUSAMMENHANG VERSTEHEN</div></div>;
  return <div className="engineering-visual visual-data" aria-hidden="true"><div className="data-field">{Array.from({length:70},(_,i)=><i key={i} style={{left:(5+i*17%90)+'%',top:(70-(i*17%90)*.53+(i*29%31))+'%',opacity:.3+(i%5)/7}}/>)}</div><span className="visual-label top-left">BEOBACHTUNG</span><span className="visual-label bottom-right">ERKENNTNIS</span><div className="visual-caption">MUSTER ERKENNEN. HYPOTHESEN PRÜFEN.</div></div>;
}
export default function SiteContent(){return <>
  <section className="capabilities" id="leistungen" aria-label="Unsere Kompetenzen">
    <div className="capabilities-heading section-wrap"><span className="section-index">02 / DREI PERSPEKTIVEN. EIN ANSPRUCH.</span><p>Qualität entwickeln.<br/>Risiken verstehen. Daten nutzen.</p></div>
    {services.map((s,i)=><article className={'capability-panel capability-'+i} key={s.slug}>
      <div className="capability-inner"><div className="capability-number">0{i+1} / QONSUL KOMPETENZEN</div><h2>{s.title}</h2><div className="capability-copy"><h3>{s.lead}</h3><p>{s.text}</p><a className="button button-outline" href={'/leistungen/'+s.slug}>Kompetenz entdecken <span>↗</span></a></div><EngineeringVisual kind={i}/><span className="concept-note">Konzeptdarstellung</span></div>
    </article>)}
  </section>
  <section id="methode" className="approach section-wrap">
    <span className="section-index">03 / UNSER ANSATZ</span><div className="approach-heading"><h2>Von der Vermutung<br/>zur Entscheidung.</h2><p>Datenwissenschaft ist Teil unseres Vorgehens: vom Verständnis des Problems bis zur Prüfung, ob eine Maßnahme wirkt.</p></div>
    <div className="approach-steps">{[['Verstehen','Produkt, Prozess und Fehlerbild gemeinsam eingrenzen.'],['Messen','Relevante Daten und ihre Aussagekraft prüfen.'],['Analysieren','Hypothesen untersuchen und Risikotreiber quantifizieren.'],['Verbessern','Maßnahmen priorisieren und ihre Wirkung nachweisen.']].map(([title,text],i)=><article key={title}><span>0{i+1}</span><h3>{title}</h3><p>{text}</p></article>)}</div>
    <div className="practice-examples"><span className="section-index">TYPISCHE FRAGESTELLUNGEN / ILLUSTRATIVE BEISPIELE</span><details><summary>Warum fällt ein Bauteil nur unter bestimmten Temperaturen aus?<span>+</span></summary><p>Prüfprofile, Materialeigenschaften und Messsystem gemeinsam betrachten. Temperatur- und Ausfalldaten synchronisieren, mögliche Einflussfaktoren eingrenzen und die Hypothese durch gezielte Versuche prüfen.</p></details><details><summary>Was steckt hinter zunehmender Ausschussquote bei einzelnen Chargen?<span>+</span></summary><p>Chargeninformationen mit Prozessparametern und Prüfmerkmalen verbinden. Unterschiede zwischen vergleichbaren Gut- und Schlechtteilen untersuchen, Störfaktoren berücksichtigen und die Wirkung einer Änderung messen.</p></details><small>Die Beispiele zeigen unser Vorgehen. Sie sind keine Kundenreferenzen oder Ergebnisversprechen.</small></div>
  </section>
  <section className="about-section" id="ueber-uns"><div className="section-wrap about-inner"><span className="section-index">04 / ÜBER QONSUL</span><h2>Technisches Verständnis.<br/>Analytische Tiefe.</h2><div className="about-columns"><p>QONSUL ist eine Managementberatung aus Oberboihingen mit einem klaren Schwerpunkt: datengetriebenes Qualitäts- und Risikomanagement für die Produktentwicklung.</p><div><p>Wir verbinden Qualitätsmethoden, technische Zusammenhänge und quantitative Analyse. Gemeinsam mit Ihrem Team schaffen wir nachvollziehbare Entscheidungsgrundlagen und übersetzen Erkenntnisse in konkrete nächste Schritte.</p><a className="text-link" href="#analyse">Unsere Arbeitsweise kennenlernen ↗</a></div></div><div className="about-signature">DATA <span>×</span> QUALITY <span>×</span> RISK</div></div></section>
  <section className="insights section-wrap" id="insights"><div className="section-heading"><div><span className="section-index">PERSPEKTIVEN / QONSUL INSIGHTS</span><h2>Wissen, das weiterführt.</h2></div><p>Impulse für Qualität,<br/>Risiko und datenbasierte Entscheidungen.</p></div><div className="editorial-list">{articles.map((a,i)=><a href={'/insights/'+a.slug} key={a.slug}><span className="article-index">0{i+1}</span><div><span className="eyebrow">{a.tag}</span><h3>{a.title}</h3><p>{a.description}</p></div><span className="article-time">{a.time}</span><span className="article-arrow">↗</span></a>)}</div></section>
</>;}
