export const articles=[
  {slug:'ishikawa-in-engineering',tag:'URSACHENANALYSE',time:'3 Min. Lesezeit',title:'Eine Hypothese ist noch keine Ursache.',description:'Wie ein Ishikawa-Diagramm den Weg vom ersten Verdacht zum überprüfbaren nächsten Schritt öffnet.',sections:[
    {title:'Mit einer Beobachtung beginnen',text:'Formulieren Sie das Problem so, dass andere es nachvollziehen können: welches Bauteil, welcher Fehler, unter welchen Bedingungen? Halten Sie Vermutungen zunächst getrennt. „Ausfall bei erhöhter Temperatur“ ist eine Beobachtung; die Ursache bleibt zu untersuchen.'},
    {title:'Perspektiven systematisch verbinden',text:'Betrachten Sie Produkt, Prozess, Material, Mensch, Messung und Umgebung. Die Kategorien sind eine Arbeitshilfe für das gemeinsame Denken. Eine leere Kategorie kann eine Wissenslücke zeigen; eine volle Kategorie beweist keine Ursache.'},
    {title:'Die nächste Prüfung festlegen',text:'Notieren Sie zu einer Hypothese, welche Beobachtung sie stützen oder infrage stellen würde. Welche Messdaten brauchen Sie? Was muss im Versuch konstant bleiben? Dokumentieren Sie auch widersprechende Ergebnisse. Das Diagramm strukturiert die Untersuchung; den Nachweis liefert die anschließende Analyse.'}
  ],source:'https://asq.org/quality-resources/fishbone',sourceLabel:'ASQ: Fishbone diagram'},
  {slug:'fmea-mit-daten',tag:'RISK ENGINEERING',time:'3 Min. Lesezeit',title:'Risiken bewerten. Annahmen hinterfragen.',description:'Wie Prüf- und Felddaten eine FMEA ergänzen können, ohne Unsicherheit hinter einer Kennzahl zu verstecken.',sections:[
    {title:'Wissen und Annahmen trennen',text:'Eine FMEA strukturiert mögliche Fehler, ihre Folgen und Ursachen. Dokumentieren Sie zusätzlich, worauf die Einschätzung beruht: Erfahrung, Versuch, Feldbeobachtung oder offene Annahme. So wird sichtbar, wo weitere Erkenntnisse die Entscheidung verändern könnten.'},
    {title:'Daten im Kontext betrachten',text:'Eine Fehlerquote ohne Bezugsgröße ist wenig aussagekräftig. Betrachten Sie Einsatzdauer, Stichprobe, Produktstand und Belastung. Fehlende Reklamationen belegen keine Fehlerfreiheit. Prüfen Sie, ob vorhandene Daten zum betrachteten Fehlermechanismus und Einsatzfall passen.'},
    {title:'Maßnahmen mit einer Prüffrage verbinden',text:'Legen Sie vor Umsetzung fest, wie Sie die Wirkung beobachten wollen. Eine abgeschlossene Aufgabe ist noch kein Wirksamkeitsnachweis. Prüfen Sie nach einer Änderung den betroffenen Fehlerfall und aktualisieren Sie die Risikoanalyse mit den gewonnenen Erkenntnissen.'}
  ],source:'https://asq.org/quality-resources/fmea',sourceLabel:'ASQ: Failure Mode and Effects Analysis'},
  {slug:'qualitaetsdaten-verstehen',tag:'QUALITY ANALYTICS',time:'3 Min. Lesezeit',title:'Streuung verstehen. Gezielt verbessern.',description:'Warum Mittelwerte allein wenig über die Stabilität eines Prozesses verraten.',sections:[
    {title:'Den Verlauf erhalten',text:'Ein Monatsmittel kann kurze Abweichungen verdecken. Betrachten Sie Messwerte deshalb in ihrer zeitlichen Reihenfolge und ergänzen Sie relevante Informationen wie Charge, Anlage und Parameterstand. Ein nachvollziehbarer Datensatz ist die Grundlage jeder weiteren Auswertung.'},
    {title:'Die Messung mitdenken',text:'Bevor Sie Prozessunterschiede interpretieren, prüfen Sie Einheiten, Kalibrierung und Wiederholbarkeit. Unterschiedliche Prüfmittel können unterschiedliche Signale liefern. Dokumentieren Sie deshalb, wie und unter welchen Bedingungen ein Wert entstanden ist.'},
    {title:'Signale begründet untersuchen',text:'Eine passende Regelkarte kann Hinweise auf Veränderungen im Prozess geben. Die Auswahl hängt unter anderem von Datentyp, Stichprobenbildung und Annahmen ab. Eingriffsgrenzen beschreiben das beobachtete Prozessverhalten; sie sind keine Kundentoleranzen. Ein Signal löst eine Untersuchung aus und erklärt seine Ursache noch nicht.'}
  ],source:'https://www.itl.nist.gov/div898/handbook/pmc/section3/pmc3.htm',sourceLabel:'NIST/SEMATECH: Control charts'}
];
export const services=[
  {slug:'quality-engineering',title:'Quality Engineering',lead:'Produktqualität beginnt lange vor der Freigabe.',text:'Wir verbinden Anforderungen, Entwicklungsentscheidungen und Verifikation zu einer nachvollziehbaren Qualitätsplanung. Gemeinsam mit Ihrem Team schaffen wir Klarheit über besondere Merkmale, offene Nachweise und sinnvolle nächste Schritte.',items:['Qualitätsplanung und Reifegradabsicherung in der Produktentwicklung','Anforderungen, Design Reviews und technische Risiken zusammenführen','Verifikation und Validierung an besonderen Produktmerkmalen ausrichten','Wiederkehrende Qualitätsprobleme strukturiert untersuchen']},
  {slug:'risk-engineering',title:'Risk Engineering',lead:'Risiken sichtbar machen. Entscheidungen absichern.',text:'Technische Risiken brauchen eine klare Beschreibung und eine belastbare Einordnung. Wir verbinden Methodenwissen mit verfügbaren Daten und machen Unsicherheiten transparent, damit Ihr Team Maßnahmen begründet priorisieren kann.',items:['FMEA und Fehlerbaumanalyse für Produkt- und Prozessrisiken','Szenarien, Wechselwirkungen und kritische Annahmen untersuchen','Quantitative Risikomodelle und Monte-Carlo-Analysen bedarfsgerecht einsetzen','Maßnahmen, Verantwortlichkeiten und Wirksamkeitsnachweise verbinden']},
  {slug:'quality-analytics',title:'Quality Analytics',lead:'Aus Qualitätsdaten wird Entscheidungswissen.',text:'Prüfstände, Produktion und Feldeinsatz liefern viele Signale. Wir helfen, die relevanten Daten zusammenzuführen, Qualität und Aussagekraft zu prüfen und daraus konkrete Verbesserungsentscheidungen abzuleiten.',items:['Mess-, Prüf-, Prozess- und Reklamationsdaten sinnvoll verknüpfen','Statistische Ursachenanalyse, SPC und Versuchsplanung einsetzen','Zuverlässigkeit und Einflussfaktoren mit geeigneten Modellen untersuchen','Qualitäts- und Risikokennzahlen für Entwicklung und Management aufbereiten']}
];
