import { CATEGORIES, type Analysis } from './analysis';
export const escapeHtml = (s: string) => s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export function reportHtml(analysis: Analysis, createdAt = new Date().toISOString()) {
  const e = escapeHtml;
  // Preserve categories in reports saved before the industrial-quality redesign.
  const categories=analysis.causes.some(c=>!CATEGORIES.includes(c.category))?[...new Set(analysis.causes.map(c=>c.category))]:CATEGORIES;
  const available=analysis.availableData||[];
  const sections=categories.map(category=>'<section><h2>'+e(category)+'</h2><ul>'+(
    analysis.causes.filter(c=>c.category===category).map(c=>'<li><span class="tag">'+(c.source==='user'?'EIGENE BEOBACHTUNG':c.source==='ai'?'KI-HYPOTHESE':'REGELBASIERTE HYPOTHESE')+'</span><p><strong>'+e(c.text)+'</strong></p>'+
      (c.check?'<p>Prüfen: '+e(c.check)+'</p>':'')+
      (c.data?.length?'<p>Benötigte Daten: '+c.data.map(e).join(' · ')+'</p>':'')+
      (c.metric?'<small>Möglicher Messbezug: '+e(c.metric)+'</small>':'')+'</li>').join('')||'<li>Noch keine Beobachtung erfasst.</li>')+'</ul></section>').join('');
  return '<!doctype html><html lang="de"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>QONSUL · Quality Diagnostic Report</title><style>body{font:15px/1.7 Arial,sans-serif;color:#323d4f;background:#edf0f2;margin:0}main{max-width:900px;margin:40px auto;padding:50px;background:white}header{border-bottom:2px solid #323d4f;padding-bottom:25px}h1{font-size:34px;line-height:1.2;font-weight:400}h2{font-size:21px;font-weight:500}small{color:#65798b}section{break-inside:avoid;margin-top:28px}li{margin:16px 0}p{margin:5px 0;overflow-wrap:anywhere}.tag{font-size:10px;color:#556d80;font-weight:700;letter-spacing:.06em}.note{padding:20px;background:#e9eff3;margin:22px 0}footer{border-top:1px solid #cbd4db;padding-top:20px;margin-top:35px;font-size:11px}@media(max-width:600px){main{margin:0;padding:25px}}@media print{body{background:white}main{margin:0;padding:0}a{color:inherit}@page{margin:18mm}}</style></head><body><main><header><strong>QONSUL</strong><p>DATA · QUALITY · RISK</p><h1>Quality Diagnostic</h1><small>'+e(new Date(createdAt).toLocaleDateString('de-DE'))+' · '+categories.length+' Perspektiven · '+analysis.causes.length+' Beobachtungen & Hypothesen</small></header><h2>Das Ausgangsproblem</h2><p>'+e(analysis.problem)+'</p><div class="note">Diese Analyse enthält Hypothesen, keine bestätigten Ursachen. Prüfen Sie Vorschläge mit Ihrem Team anhand geeigneter Daten und Versuche. '+(analysis.mode==='rules'?'Regelbasierte Ergänzungen aus einem redaktionellen Katalog; keine KI-Generierung.':analysis.mode==='ai'?'KI-Ergänzungen sind als solche gekennzeichnet.':'Manuell erstellte Analyse.')+'</div><section><h2>Ihre Datengrundlage</h2><p>'+(available.length?available.map(e).join(' · '):'Keine Datentypen als vorhanden markiert.')+'</p><small>Selbstauskunft zur Verfügbarkeit. Es wurden keine Dateien hochgeladen oder Messwerte analysiert. Verfügbarkeit ist kein Nachweis der Datenqualität oder einer Ursache.</small></section>'+sections+'<section class="note"><h2>Ihre nächsten drei Schritte</h2><ol><li>Wählen Sie gemeinsam zwei plausible Hypothesen und benennen Sie Verantwortliche.</li><li>Prüfen Sie Datenqualität, Messsystem und geeignete Vergleichsbedingungen. Legen Sie fest, welche Beobachtung die Hypothese stützen oder widerlegen würde.</li><li>Leiten Sie eine gezielte Maßnahme ab und bewerten Sie ihre Wirkung gegen die Ausgangslage.</li></ol></section><footer>QONSUL · Vertraulicher Team-Report · Enthält keine Kontaktdaten.<br>Im Browser drucken und „Als PDF speichern“ wählen.<br>Methodischer Bezug: <a href="https://asq.org/quality-resources/fishbone">ASQ: Fishbone diagram</a>.</footer></main></body></html>';
}
