'use client';
import Brand from '@/app/brand';
import Link from 'next/link';
import {useEffect,useState} from 'react';
import type {Analysis} from '@/lib/analysis';
import {downloadIshikawaPdf} from '@/lib/ishikawa-pdf';
type SavedReport={analysis:Analysis;html:string;expiresAt:number;crmStatus:string;crmConsent:boolean};
export default function Report(){
  const [report,setReport]=useState<SavedReport|null>(null),[error,setError]=useState(''),[token]=useState(()=>typeof window==='undefined'?'':window.location.hash.slice(1)),[confirmation,setConfirmation]=useState(false),[deleted,setDeleted]=useState(false),[deleting,setDeleting]=useState(false),[deletionNotice,setDeletionNotice]=useState('');
  useEffect(()=>{if(!token)return;void fetch('/api/reports',{headers:{Authorization:`Bearer ${token}`}}).then(async r=>{const data=await r.json() as SavedReport & {error?:string};if(!r.ok)throw new Error(data.error);setReport(data);}).catch(e=>setError(e instanceof Error?e.message:'Report konnte nicht geladen werden.'));},[token]);
  async function remove(){setDeleting(true);try{const response=await fetch('/api/reports',{method:'DELETE',headers:{Authorization:`Bearer ${token}`}});const data=await response.json() as {error?:string;crmNotice:string};if(!response.ok)throw new Error(data.error);setDeleted(true);setDeletionNotice(data.crmNotice);setReport(null);window.history.replaceState(null,'','/report');}catch(e){setError(e instanceof Error?e.message:'Löschen fehlgeschlagen.');}finally{setDeleting(false);}}
  const displayError=!token?'Dieser Report-Link enthält keinen Zugriffsschlüssel.':error;
  return <><header className="header"><Link href="/" className="brand"><Brand/></Link><Link className="button button-outline" href="/">← Zur Website</Link></header><main className="report-page">{deleted?<div className="save-success"><h1>Report gelöscht.</h1><p>Ihre Analyse und Kontaktdaten wurden aus dem Website-Speicher entfernt. Der Zugriffsschlüssel ist ungültig.</p>{deletionNotice&&<p>{deletionNotice} <Link href="/datenschutz">Kontakt zum Verantwortlichen</Link></p>}<Link className="button button-green" href="/">Neue Analyse starten</Link></div>:<><div className="report-toolbar"><div><div className="eyebrow">IHRE ERKENNTNISSE. GRIFFBEREIT.</div><h1>Ihr Ishikawa-Report</h1>{report&&<p>Verfügbar bis {new Date(report.expiresAt).toLocaleDateString('de-DE')} · Link vertraulich behandeln.</p>}</div>{report&&<button className="button button-green" onClick={()=>downloadIshikawaPdf(report.analysis,false)}>Ishikawa als DIN-A4-PDF herunterladen ↧</button>}</div>{displayError&&<p className="error-message" role="alert">{displayError}</p>}{!displayError&&!report&&<p role="status">Ihr Report wird geladen …</p>}{report&&<><iframe className="report-frame" title="Vollständiger Ishikawa-Report" srcDoc={report.html} sandbox=""/><div className="report-delete"><p>Sie können die Speicherung jederzeit widerrufen und die Daten löschen.</p>{confirmation?<div className="inline-confirm"><span>Report und Kontaktdaten endgültig löschen?</span><button className="button button-outline" onClick={()=>setConfirmation(false)}>Abbrechen</button><button className="button button-dark" disabled={deleting} onClick={remove}>{deleting?'Wird gelöscht …':'Endgültig löschen'}</button></div>:<button className="quiet-button" onClick={()=>setConfirmation(true)}>Report und Kontaktdaten löschen</button>}</div></>}</>}</main></>;
}
