'use client';
import Brand from '@/app/brand';
import {useEffect,useState} from 'react';
import type {Analysis} from '@/lib/analysis';
import {downloadIshikawaPdf} from '@/lib/ishikawa-pdf';
type SavedReport={analysis:Analysis;html:string;expiresAt:number;crmStatus:string;crmConsent:boolean};
export default function Report(){
  const [report,setReport]=useState<SavedReport|null>(null),[error,setError]=useState(''),[token,setToken]=useState(''),[confirmation,setConfirmation]=useState(false),[deleted,setDeleted]=useState(false),[deleting,setDeleting]=useState(false),[deletionNotice,setDeletionNotice]=useState('');
  useEffect(()=>{const key=window.location.hash.slice(1);setToken(key);if(!key){setError('Dieser Report-Link enthält keinen Zugriffsschlüssel.');return;}fetch('/api/reports',{headers:{Authorization:`Bearer ${key}`}}).then(async r=>{const data=await r.json() as SavedReport & {error?:string};if(!r.ok)throw new Error(data.error);setReport(data);}).catch(e=>setError(e.message));},[]);
  async function remove(){setDeleting(true);try{const response=await fetch('/api/reports',{method:'DELETE',headers:{Authorization:`Bearer ${token}`}});const data=await response.json() as {error?:string;crmNotice:string};if(!response.ok)throw new Error(data.error);setDeleted(true);setDeletionNotice(data.crmNotice);setReport(null);window.history.replaceState(null,'','/report');}catch(e){setError(e instanceof Error?e.message:'Löschen fehlgeschlagen.');}finally{setDeleting(false);}}
  return <><header className="header"><a href="/" className="brand"><Brand/></a><a className="button button-outline" href="/">← Zur Website</a></header><main className="report-page">{deleted?<div className="save-success"><h1>Report gelöscht.</h1><p>Ihre Analyse und Kontaktdaten wurden aus dem Website-Speicher entfernt. Der Zugriffsschlüssel ist ungültig.</p>{deletionNotice&&<p>{deletionNotice} <a href="/datenschutz">Kontakt zum Verantwortlichen</a></p>}<a className="button button-green" href="/">Neue Analyse starten</a></div>:<><div className="report-toolbar"><div><div className="eyebrow">IHRE ERKENNTNISSE. GRIFFBEREIT.</div><h1>Ihr Ishikawa-Report</h1>{report&&<p>Verfügbar bis {new Date(report.expiresAt).toLocaleDateString('de-DE')} · Link vertraulich behandeln.</p>}</div>{report&&<button className="button button-green" onClick={()=>downloadIshikawaPdf(report.analysis,false)}>Ishikawa als DIN-A4-PDF herunterladen ↧</button>}</div>{error&&<p className="error-message" role="alert">{error}</p>}{!error&&!report&&<p role="status">Ihr Report wird geladen …</p>}{report&&<><iframe className="report-frame" title="Vollständiger Ishikawa-Report" srcDoc={report.html} sandbox=""/><div className="report-delete"><p>Sie können die Speicherung jederzeit widerrufen und die Daten löschen.</p>{confirmation?<div className="inline-confirm"><span>Report und Kontaktdaten endgültig löschen?</span><button className="button button-outline" onClick={()=>setConfirmation(false)}>Abbrechen</button><button className="button button-dark" disabled={deleting} onClick={remove}>{deleting?'Wird gelöscht …':'Endgültig löschen'}</button></div>:<button className="quiet-button" onClick={()=>setConfirmation(true)}>Report und Kontaktdaten löschen</button>}</div></>}</>}</main></>;
}
