import Brand from '@/app/brand';
import { setting } from '@/lib/server';
import Link from 'next/link';

export const metadata = { title: 'Datenschutzhinweise · QONSUL' };

export default function Datenschutz(): React.ReactNode {
  const email = setting('PUBLIC_CONTACT_EMAIL');
  const retention = Math.min(730, Math.max(30, Number(setting('CONTACT_RETENTION_DAYS')) || 90));
  const aiActive = !!setting('OPENAI_API_KEY');
  const productionReady = setting('PRODUCTION_READY') === 'true';

  return <>
    <header className="header"><Link className="brand" href="/"><Brand /></Link><Link href="/" className="button button-outline">← Zur Startseite</Link></header>
    <main className="legal-page">
      <div className="eyebrow">TRANSPARENZ & DATENSCHUTZ</div>
      <h1>Ihre Daten. Ihre Entscheidung.</h1>
      {!productionReady && <p className="preview-note">Entwurf vor dem öffentlichen Launch. Die abschließende vertragliche Dokumentation mit eingesetzten Dienstleistern wird vor produktiver Nutzung bestätigt; die unten beschriebenen Verarbeitungen und Fristen entsprechen bereits dem für den Launch vorgesehenen Stand.</p>}
      <section><h2>1. Verantwortlicher</h2><p>{setting('LEGAL_ENTITY_NAME') || 'Anbieter und Rechtsform noch zu ergänzen.'}<br />{setting('LEGAL_ADDRESS') || 'Ladungsfähige Anschrift noch zu ergänzen.'}</p><p>{email ? <a href={`mailto:${email}`}>{email}</a> : 'Kontakt für Datenschutzanfragen: vor Freigabe zu hinterlegen.'}</p></section>
      <section><h2>2. Website-Aufruf und Hosting-Infrastruktur</h2><p>Die manuelle Ishikawa-Analyse bleibt zunächst im Arbeitsspeicher Ihres Browsers. Wir setzen keine Marketing-Cookies, Werbepixel oder extern geladenen Schriftarten ein. Der direkte DIN-A4-PDF-Download wird vollständig im Browser erzeugt und benötigt keine Kontaktangaben. Beim Schließen oder Neuladen der Seite geht eine ungespeicherte Analyse verloren.</p><p>Diese Website läuft technisch auf Cloudflare (Worker-Ausführung, Sicherheits- und Auslieferungsinfrastruktur, Datenbank Cloudflare D1 für Kontaktanfragen und gespeicherte Reports). Beim Abruf der Website verarbeitet Cloudflare als technischer Infrastrukturanbieter die dafür erforderlichen Verbindungs- und Protokolldaten. Es werden keine funktionsfremden Cookies gesetzt.</p></section>
      <section><h2>3. Optionale Website-Analyse</h2><p>Auf dieser Website können Sie einer zusätzlichen, ausschließlich pseudonymen Nutzungsanalyse zustimmen. Ohne Ihre Zustimmung findet keine Analyse statt und keine der unten genannten Kennungen wird angelegt. Ihre Entscheidung wird ausschließlich lokal in Ihrem Browser gespeichert (Local Storage), nicht als Cookie; Sie können sie jederzeit über den Hinweis „Website-Analyse: aktiv/deaktiviert“ ändern oder widerrufen. Die Nutzung des Kontaktformulars, der Ishikawa-Analyse und aller sonstigen Website-Funktionen ist unabhängig von dieser Entscheidung uneingeschränkt möglich. Diese Analyse-Einwilligung ist rechtlich getrennt von der Einwilligung zur Speicherung eines Reports, zur Beratungsanfrage und von der Bestätigung der Kontaktformular-Hinweise; eine Einwilligung wird nicht automatisch für einen anderen Zweck verwendet.</p><p>Bei Zustimmung erfassen wir ausschließlich kontrollierte, technische Ereignisse: aufgerufene Seiten, Verweildauer/Scrolltiefe, Klicks auf definierte Handlungsflächen (z. B. Kontakt-Button, Analyse-starten-Button) sowie den Start und Abschluss der Ishikawa-Analyse bzw. einer abgeschickten Kontaktanfrage. Übermittelt werden dabei ausschließlich technische Kennungen und die genannten Ereignistypen – niemals Ihre Problembeschreibung, eigene Ursachen, Nachrichtentext, Name, E-Mail-Adresse oder sonstige Formularinhalte. UTM-Parameter aus dem Aufruflink (utm_source, utm_medium, utm_campaign, utm_content, utm_term) werden zur Herkunftsauswertung mit erfasst, sofern in der URL vorhanden; sonstige Adressparameter werden nicht gespeichert. Es findet kein Browser-Fingerprinting und keine Zusammenführung mit Ihrer Identität statt.</p><p>Eine zufällige, pseudonyme Sitzungskennung wird ausschließlich in der Sitzungsspeicherung Ihres Browsers (Session Storage) gehalten und endet spätestens mit dem Schließen des Browser-Tabs. Bei mehr als 30 Minuten Inaktivität oder spätestens 24 Stunden nach ihrer Erstellung wird bei weiterer Nutzung eine neue Kennung vergeben. Die pseudonymen Ereignisdaten werden beim von QONSUL betriebenen QONSUL Cockpit für bis zu 90 Tage als Rohdaten und anschließend ausschließlich als anonymisierte, aggregierte Kennzahlen für bis zu 24 Monate verarbeitet.</p></section>
      <section><h2>4. Kontaktformular</h2><p>Wenn Sie uns schreiben, verarbeiten wir Name, E-Mail-Adresse, Nachricht sowie freiwillig Telefonnummer und Unternehmen, um Ihre Anfrage zu beantworten und vorvertragliche oder geschäftliche Kommunikation zu führen. Rechtsgrundlage ist je nach Inhalt Art. 6 Abs. 1 lit. b DSGVO oder unser berechtigtes Interesse an der Bearbeitung geschäftlicher Anfragen nach Art. 6 Abs. 1 lit. f DSGVO. Die Kenntnisnahme der Hinweise ist keine Einwilligung in Werbung oder Newsletter.</p><p>Die Anfrage wird zunächst in der Website-Datenbank (Cloudflare D1) für {retention} Tage gespeichert. Im produktiven Betrieb wird sie zusätzlich verschlüsselt an das von QONSUL betriebene QONSUL Cockpit zur Bearbeitung als Geschäftsanfrage übertragen. Für den E-Mail-Versand einer internen Zusammenfassung an {email || 'die QONSUL-Kontaktadresse'} setzen wir den Versanddienstleister Resend ein; die E-Mail wird anschließend im Microsoft-365-Postfach von QONSUL empfangen und dort weiterbearbeitet. Bei Resend sind Öffnungs- und Link-Tracking für diese Versände deaktiviert. Telefon und Unternehmen sind freiwillig. Ohne produktive Konfiguration werden diese Übertragungen nicht ausgeführt.</p></section>
      <section><h2>5. Ishikawa-Ursachenanalyse und KI-gestützte Vorschläge</h2><p>Der Vorschlags-Button übermittelt die Problembeschreibung, eigene Ursachen und ausgewählte Datentypen an unseren Server. Die Dateninventur erfasst ausschließlich Kategorien per Selbstauskunft; sie lädt keine Dateien oder Messwerte hoch. {aiActive ? 'KI-gestützte Vorschläge über OpenAI sind aktuell aktiv konfiguriert; die Weitergabe an OpenAI erfolgt in diesem Fall erst nach Ihrer gesonderten Einwilligung.' : 'KI-gestützte Vorschläge über OpenAI sind aktuell nicht aktiv; es werden ausschließlich die vorbereiteten regelbasierten Vorschläge angewandt, und es werden keine Daten an OpenAI übermittelt.'} Offensichtliche E-Mail-Adressen, URLs, IPv4-Adressen und bestimmte API-Schlüssel werden vorab entfernt. Das ist keine vollständige Anonymisierung, sondern eine Bereinigung erkennbarer Muster: Bitte keine Personen-, Kunden- oder Geheimdaten eingeben.</p><p>Sofern KI-gestützte Vorschläge aktiv sind, verwendet die API-Anfrage store:false. Dies bedeutet nicht automatisch, dass der Anbieter keinerlei Sicherheits- oder Missbrauchsprotokolle führt. Verarbeitung, Drittlandtransfers und mögliche weitere Speicherdauern sind vor einer etwaigen Aktivierung vertraglich geprüft. Kontaktdaten werden nicht an die KI gesendet. KI-Ergebnisse sind Hypothesen, keine bestätigten Ursachen.</p></section>
      <section><h2>6. Report speichern und Beratungsanfrage</h2><p>Mit Ihrer Einwilligung speichern wir Name, E-Mail, Unternehmen, die vollständige Analyse, Einwilligungsstand und Zeitpunkt in einer D1-Datenbank. Zugriff erfolgt über einen zufälligen persönlichen Schlüssel; in der Datenbank liegt nur dessen Hash. Jeder mit dem vertraulichen Link kann den Report lesen und löschen. Reports sind nach 30 Tagen nicht mehr abrufbar und werden anschließend über die Wartungsroutine gelöscht.</p><p>Nur mit separatem Opt-in werden Kontaktangaben und vollständige Analyse verschlüsselt an das von QONSUL betriebene QONSUL Cockpit übermittelt. Das Opt-in umfasst eine persönliche Kontaktaufnahme zu dieser Anfrage, keinen Newsletter. Eine Löschung des Website-Reports entfernt bereits in das Cockpit übermittelte Geschäftsunterlagen nicht automatisch; hierfür wenden Sie sich an den Verantwortlichen.</p></section>
      <section><h2>7. Aggregierte Trenddaten und Missbrauchsschutz</h2><p>Nach zusätzlicher Einwilligung zählen wir ausschließlich Ursachen je Kategorie und Quartal. Freitexte, Kontakte und Einzelereignisse werden nicht in die Trendtabelle übernommen. Aggregierte Zähler lassen sich keiner Analyse mehr zuordnen.</p><p>Zur Begrenzung von Anfragen nutzt der Server einen stündlich wechselnden Hash aus IP-Adresse, Salt und Zeitfenster. Rohe IP-Adressen werden dafür nicht in der Anwendungsdatenbank gespeichert. Abgelaufene Zähler werden automatisch entfernt.</p></section>
      <section><h2>8. Empfänger und eingesetzte Dienste</h2><p>Empfänger können – jeweils nur soweit aktiviert und tatsächlich genutzt – sein: Cloudflare als Hosting- und Infrastrukturanbieter (Worker-Ausführung, D1-Datenbank), Resend für den Versand der internen Kontaktzusammenfassung, Microsoft 365 als empfangendes Postfach von QONSUL, das von QONSUL betriebene QONSUL Cockpit für die Bearbeitung von Kontakt-, Analyse- und Beratungsanfragen sowie für die pseudonyme Website-Analyse, und – nur soweit aktiv konfiguriert – OpenAI für gesondert freigegebene KI-gestützte Vorschläge. Die Bereitstellung der Pflichtfelder im Kontaktformular ist zur Bearbeitung erforderlich; ohne sie können wir nicht antworten. Eine ausschließlich automatisierte Entscheidung mit rechtlicher oder ähnlich erheblicher Wirkung findet nicht statt.</p></section>
      <section><h2>9. Aufbewahrungsfristen im Überblick</h2><p>Website-Analyse (sofern eingewilligt): Rohdaten bis zu 90 Tage, danach ausschließlich anonymisierte, aggregierte Kennzahlen bis zu 24 Monate. Gespeicherte Ishikawa-Reports: 30 Tage. Kontaktanfragen in der Website-Datenbank: {retention} Tage. Geschäftliche Anfragen ohne anschließenden Auftrag werden im QONSUL Cockpit in der Regel für 90 Tage vorgehalten, Projektunterlagen zu beauftragten Vorhaben für 3 Jahre. Für steuer- und handelsrechtlich relevante Unterlagen gelten je nach Dokumentart die gesetzlichen Aufbewahrungsfristen von 6, 8 oder 10 Jahren. Nach Ablauf der jeweils maßgeblichen Frist werden die betreffenden Daten gelöscht oder anonymisiert, soweit keine gesetzliche Aufbewahrungspflicht entgegensteht.</p></section>
      <section><h2>10. Ihre Rechte</h2><p>Sie können Auskunft, Berichtigung, Löschung, Einschränkung und gegebenenfalls Datenübertragbarkeit verlangen. Sie können einer Verarbeitung auf Grundlage berechtigter Interessen widersprechen und Einwilligungen mit Wirkung für die Zukunft widerrufen. Außerdem können Sie sich bei einer Datenschutzaufsichtsbehörde beschweren, insbesondere beim <a href="https://www.baden-wuerttemberg.datenschutz.de/" target="_blank" rel="noreferrer">Landesbeauftragten für den Datenschutz und die Informationsfreiheit Baden-Württemberg ↗</a>.</p><p>Rechtliche Grundlage: <a href="https://eur-lex.europa.eu/legal-content/DE/TXT/?uri=CELEX:32016R0679" target="_blank" rel="noreferrer">Datenschutz-Grundverordnung, insbesondere Art. 5–7, 12–22 und 44 ff. ↗</a>.</p></section>
    </main>
  </>;
}
