from __future__ import annotations

import base64
from io import BytesIO
from pathlib import Path

from PIL import Image


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "public" / "qonsul-logo-pdf.png"
TARGET = ROOT / "lib" / "qonsul-logo-pdf.ts"


with Image.open(SOURCE) as source:
    logo = source.convert("RGBA")
    bbox = logo.getchannel("A").getbbox()
    if bbox is None:
        raise ValueError("The PDF logo is fully transparent.")
    logo = logo.crop(bbox)

padding = max(4, round(logo.height * 0.012))
flattened = Image.new("RGB", (logo.width + padding * 2, logo.height + padding * 2), "white")
flattened.paste(logo, (padding, padding), logo)
if flattened.width > 1200:
    height = round(flattened.height * 1200 / flattened.width)
    flattened = flattened.resize((1200, height), Image.Resampling.LANCZOS)

buffer = BytesIO()
flattened.save(buffer, format="JPEG", quality=94, subsampling=0, optimize=True)
encoded = base64.b64encode(buffer.getvalue()).decode("ascii")
TARGET.write_text(
    "// Generated by scripts/build-pdf-logo.py from public/qonsul-logo-pdf.png.\n"
    f"export const QONSUL_PDF_LOGO_WIDTH={flattened.width};\n"
    f"export const QONSUL_PDF_LOGO_HEIGHT={flattened.height};\n"
    f"export const QONSUL_PDF_LOGO_BASE64='{encoded}';\n",
    encoding="utf-8",
    newline="\n",
)
print(f"Generated {TARGET} ({flattened.width}x{flattened.height}, {len(buffer.getvalue())} bytes)")
