import assert from 'node:assert/strict';
const base=process.env.TEST_BASE_URL||'http://localhost:3000';
if(!/^http:\/\/(localhost|127\.0\.0\.1)(:\d+)?$/.test(base))throw new Error('This mutation test only runs on an explicit local test server.');
let passed=0;
const check=(value,message)=>{assert.ok(value,message);passed++;console.log(`PASS ${message}`);};
async function request(path,body,headers={}){const r=await fetch(base+path,{method:'POST',headers:{'Content-Type':'application/json',Origin:base,...headers},body:JSON.stringify(body)});const text=await r.text();let data;try{data=JSON.parse(text);}catch{data={error:text};}return {status:r.status,data};}
const seed={problem:'Sporadische Ausfälle bei hoher Temperatur <script>alert(1)</script>',availableData:['Prüf- & Messdaten','Umgebungsdaten'],causes:[{id:'test-own',category:'Produkt',text:'Ausfälle betreffen eine bestimmte Baugruppe',source:'user'}]};
const status=await (await fetch(base+'/api/status')).json();assert.equal(status.productionReady,false,'Only test in private preview mode');assert.equal(status.ai,false,'Do not spend API credits in this test');
assert.equal(status.contactReady,false,'Do not send external CRM or email messages in preview tests');
const badOrigin=await request('/api/analyze',seed,{Origin:'https://evil.example'});check([400,403].includes(badOrigin.status),'Cross-origin analysis rejected');
const invalid=await request('/api/analyze',{problem:'bad',causes:[]});check(invalid.status===400,'Short problem rejected');
const malformed=await request('/api/analyze',{...seed,causes:[{category:'__proto__',text:'Invalid category',source:'user'}]});check(malformed.status===400,'Unknown category rejected');
const large=await request('/api/analyze',{...seed,padding:'x'.repeat(25000)});check(large.status===400,'Oversized payload rejected');
check((await request('/api/analyze',{...seed,availableData:['secret-field']})).status===400,'Unknown data kind rejected');
const start=performance.now();const result=await request('/api/analyze',seed);const elapsed=Math.round(performance.now()-start);check(result.status===200,'Analysis endpoint works');check(result.data.mode==='rules'&&result.data.causes.length===12,'Twelve explicitly rule-based hypotheses returned');check(new Set(result.data.causes.map(c=>c.category)).size===6,'Every category is covered');check(result.data.causes.every(c=>c.check&&c.metric&&c.data.length&&c.source==='rules'),'Suggestions contain validation steps, data needs and industrial-quality metrics');console.log(`Rule response: ${elapsed} ms`);
const payload={analysis:{...seed,causes:[...seed.causes,...result.data.causes]},name:'Test Person',email:'qa-test@example.invalid',company:'Fiktives Testunternehmen',consentVersion:'2026-08-30-v1',storageConsent:false,crmConsent:false,trendConsent:false,demoConfirmed:true,reportToken:crypto.randomUUID()+crypto.randomUUID()};
check((await request('/api/reports',payload)).status===400,'Storage requires explicit consent');
check((await request('/api/reports',{...payload,storageConsent:true,demoConfirmed:false})).status===400,'Preview requires test-data confirmation');
let created=false;
try{
  const saved=await request('/api/reports',{...payload,storageConsent:true});check(saved.status===201,'Report persists in D1');created=true;check(saved.data.crmStatus==='not_requested','No CRM transfer without opt-in');check(saved.data.url.endsWith('#'+payload.reportToken),'Access token remains in URL fragment');
  const repeat=await request('/api/reports',{...payload,storageConsent:true});check(repeat.status===200&&repeat.data.url===saved.data.url,'Retry reuses existing report');
  check((await fetch(base+'/api/reports')).status===404,'Anonymous report access rejected');
  check((await fetch(base+'/api/reports',{headers:{Authorization:'Bearer '+crypto.randomUUID()+crypto.randomUUID()}})).status===404,'Wrong token rejected');
  const r=await fetch(base+'/api/reports',{headers:{Authorization:'Bearer '+payload.reportToken}});const data=await r.json();check(r.status===200&&data.analysis.causes.length===13,'Saved report preserves own and generated causes');check(!data.html.includes('<script>')&&data.html.includes('&lt;script&gt;'),'Report HTML escapes user content');check(!data.html.includes('qa-test@example.invalid'),'Download contains no contact data');check(data.analysis.availableData.length===2&&data.html.includes('Umgebungsdaten'),'Available data survives storage and appears in report');check(data.analysis.causes.filter(c=>c.source==='rules').every(c=>c.data.length),'Report retains data requirements');check(r.headers.get('cache-control')==='no-store','Sensitive report cannot be cached');
  const removed=await fetch(base+'/api/reports',{method:'DELETE',headers:{Authorization:'Bearer '+payload.reportToken,Origin:base}});check(removed.status===200,'Report can be deleted');created=false;check((await fetch(base+'/api/reports',{headers:{Authorization:'Bearer '+payload.reportToken}})).status===404,'Deleted report is inaccessible');
}finally{if(created)await fetch(base+'/api/reports',{method:'DELETE',headers:{Authorization:'Bearer '+payload.reportToken,Origin:base}});}
const contactToken=crypto.randomUUID();const contact={name:'Fiktive Kontaktperson',email:'qa-contact@example.invalid',phone:'+49 000 000000',company:'Fiktives Prüflabor',message:'Dies ist eine ausschließlich fiktive Testanfrage für die lokale Qualitätsprüfung.',privacyVersion:'2026-08-31-v1',privacyAcknowledged:true,demoConfirmed:true,clientToken:contactToken};
check((await request('/api/contact',{...contact,privacyAcknowledged:false})).status===400,'Contact form requires privacy acknowledgement');
check((await request('/api/contact',{...contact,demoConfirmed:false})).status===400,'Contact preview requires fictional-data confirmation');
let contactCreated=false;try{const inquiry=await request('/api/contact',contact);check(inquiry.status===201&&inquiry.data.stored===true,'Contact inquiry persists in D1');contactCreated=true;check(inquiry.data.crmStatus==='not_configured'&&inquiry.data.emailStatus==='not_configured','Preview inquiry triggers no external delivery');const repeated=await request('/api/contact',contact);check(repeated.status===200&&repeated.data.stored===true,'Contact retry is idempotent');const removed=await fetch(base+'/api/contact',{method:'DELETE',headers:{Authorization:'Bearer '+contactToken,Origin:base}});check(removed.status===200,'Contact test record can be removed');contactCreated=false;}finally{if(contactCreated)await fetch(base+'/api/contact',{method:'DELETE',headers:{Authorization:'Bearer '+contactToken,Origin:base}});}
for(const [path,title] of [['/','QONSUL'],['/datenschutz','Datenschutzhinweise'],['/impressum','Impressum'],['/insights/ishikawa-in-engineering','Eine Hypothese'],['/insights/fmea-mit-daten','Risiken bewerten'],['/insights/qualitaetsdaten-verstehen','Streuung verstehen'],['/leistungen/quality-engineering','Quality Engineering'],['/leistungen/risk-engineering','Risk Engineering'],['/leistungen/quality-analytics','Quality Analytics']]){const r=await fetch(base+path);const html=await r.text();check(r.status===200&&html.includes(title),`Route renders: ${path}`);if(path.startsWith('/insights/')||path.startsWith('/leistungen/'))check(!html.includes('property="og:image"'),`Detail route has no inherited generic social image: ${path}`);}
check((await fetch(base+'/insights/not-an-article')).status===404,'Unknown article returns 404');
check((await request('/api/maintenance',{})).status===401,'Maintenance requires authorization');
console.log(`\n${passed} API and route checks passed.`);
